%% Generate a lookup table for x^3 * K_{2/3}(x)
clear; clc;

func = @(x) x.^3 .* besselk(2/3, x);

lbLower = 1e-3;     % Lower lambda_c/lambda bound
lbUpper = 1e2;      % Upper -- " --
lambda = logspace(log10(lbLower), log10(lbUpper), 100);

power=zeros(size(lambda));
for i=1:numel(lambda)
    power(i) = func(lambda(i));
end

n=num2str(numel(lambda));

%%

fid=fopen('pcyl_lookup_pol.c','w');
fwrite(fid, ['/* This file was automatically generated by `genlookup_delta_pol.m` */',10,10]);
fwrite(fid, ['const int sycamera_pcyl_lookup_pol_count = ',n,';',10]);
fwrite(fid, ['const double sycamera_pcyl_lookup_pol_lambda[',n,'] = {',10]);
for i=1:numel(lambda)
    if mod(i,10) == 1
        fwrite(fid, 9);
    end
    
    % Write the number
    fwrite(fid, num2str(lambda(i),16));
    
    if i < numel(lambda)
        fwrite(fid, ',');
    end
    if mod(i,10) == 0
        fwrite(fid, 10);
    end
end

fwrite(fid, ['};',10,10]);

fwrite(fid, ['const double sycamera_pcyl_lookup_pol_int[',n,'] = {',10]);
for i=1:numel(power)
    if mod(i,10) == 1
        fwrite(fid, 9);
    end
    
    % Write the number
    fwrite(fid, num2str(power(i),16));
    
    if i < numel(power)
        fwrite(fid, ',');
    end
    if mod(i,10) == 0
        fwrite(fid, 10);
    end
end

fwrite(fid, '};');
fclose(fid);
